name = "PkgButlerEngine"
uuid = "5c9c0fc8-7103-448b-bb0a-c427020e3b0b"
version = "1.0.4-DEV"

[deps]
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1"
Mustache = "0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
